from .src.scripts.simulation_data_generator.dynamic.generate_social_score import generate_social_score
from .src.scripts.simulation_data_generator.dynamic.simulation_data_dynamic import simulation_data_dynamic
from .src.models.working_model.tomnet2 import tomnet2
